version: '3.9'

services:
  
  wechat:
    container_name: wechat_service
    restart: always
    volumes:
      - .:/apps
    
    ports:
      - "5001:5000"
    env_file:
      - ./prod.env

    build:
      context: .
    image: timvel/wechat_service
    command: ['sanic',"-H0.0.0.0",'-p 5000','app.app']