version: '3.9'
services:
  wechat:
    container_name: wechat_service
    restart: always    
    ports:
      - "5001:5000"
    env_file:
      - ./prod.env
    networks:
      - internal
    depends_on:
      - nginx
      - redis
    build:
      context: .
    image: registry.cn-hangzhou.aliyuncs.com/timvel/wechat_service
    command: ['sanic',"-H0.0.0.0",'-p 5000','app.app']

  redis:
    container_name: redis
    image: redis
    restart: always
    sysctls:
      - net.core.somaxconn=1024
    networks:
      - internal
  nginx:
    container_name: nginx
    image: nginx
    network_mode: "host"
    volumes:
      - ./nginx:/etc/nginx/:ro
    restart: always
networks:
  internal: