version: '3.9'
services:
  wechat:
    container_name: wechat_service
    restart: always    
    ports:
      - "5001:5000"
    env_file:
      - ./prod.env
    networks:
      - timvel
    depends_on:
      - redis
    build:
      context: .
    image: registry.cn-hangzhou.aliyuncs.com/timvel/wechat_service
    command: ['sanic',"-H0.0.0.0",'-p 5000','app.app']

  redis:
    container_name: redis
    image: redis
    restart: always
    sysctls:
      - net.core.somaxconn=1024
    networks:
      - timvel
networks:
  timvel:
      name: timvel-network